# Generated by Django 6.1 on 2026-08-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Post sarlavhasi')),
                ('image', models.ImageField(upload_to='posts/', verbose_name='Post Kontent')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
